### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by darianmorat** [magdyamr542/vim-find-highlight#2]
I think your extension is superior to the QUICK SCOPE one, cause actually matches the words as it is, and we can change even the colors. that is absolutely perfect... But the performance is x5 worse.... There's any way to fix it? It would make of this extension the best quick scope

**Comment by magdyamr542** [comment]
Thanks for your feedback. I will have a look at this when i have time for it. I also don't notice a huge performance effect on my mac. Can you please let me know what your expectation is of how the performance should be? In other words, how would you measure it?

**Comment by darianmorat** [comment]
Sure... This is your extension: 
https://github.com/magdyamr542/vim-find-highlight/assets/80854633/03da1311-0d68-4437-9edf-b61cf792d8a8

And this one is the [quick-scope](https://marketplace.visualstudio.com/items?itemName=skattyadz.vscode-quick-scope)
https://github.com/magdyamr542/vim-find-highlight/assets/80854633/22938573-e293-4505-b0cb-68b5527f287a

Yours is much more as the original one, but that would be the only thing. sure more things like toggling the extension just when the f or t are pressed would be just the best but I know is not as simple as just asking for it.

**Comment by magdyamr542** [comment]
ok thanks. I will give it a look and let you know. There are some array operations and regex operations that can probably be improved.

**Comment by darianmorat** [comment]
> ok thanks. I will give it a look and let you know. There are some array operations and regex operations that can probably be improved.

Thanks to you for the effort. I appreciate a lot that

**Comment by magdyamr542** [comment]
I will close this issue now. The new version should be much faster `v0.0.7` thanks to Sergio.
You can now start using the new version @darianmorat 
Check comment: https://github.com/magdyamr542/vim-find-highlight/pull/4#issuecomment-2114948657
