### ISSUE TITLE
Trigger extension when key is pressed 

### ISSUE THREAD

**Issue by VettaStar** [magdyamr542/vim-find-highlight#3]
The extension always have the highlight present, is a bit distracting I would say. Implementing a way to trigger the extension when `f-F` and `t-T` are pressed, like [Quick Scope IDEA](https://github.com/unblevable/quick-scope) would make it much better to use and really helpful.

**Comment by magdyamr542** [comment]
Thanks for the feedback. I will take a look at it when i have time for it. The feature is not that complicated to build actually so i think i will do it but can't promise when exactly since i have very little time at the moment.

**Comment by ms007** [comment]
I would also apreciate this change. When it's always on, it's a bit distracting. I uninistalled it, but with this change it would be in my beloved plugins catalogue.

**Comment by magdyamr542** [comment]
@VettaStar @ms007 , this was deployed today in v0.0.10 thanks to @scastlara. I will close the issue.

**Comment by ms007** [comment]
Very nice
Will the documentation be updated as well?

**Comment by scastlara** [comment]
It is updated @ms007 ! There is a new commands section in the readme and the new setting is also there.
